--- ./Src/Zle/zle_bindings.c	2009-04-18 04:56:18.000000000 -0700
+++ zle_bindings-modified_for_rose.c	2012-11-05 11:56:24.000000000 -0800
@@ -48,38 +48,577 @@
 # define BR(X) X
 struct intwidget {
     int flags;
     Thingy first;
     ZleIntFunc fn;
 }
 #endif /* !HAVE_UNION_INIT */
 widgets[] = {
 #define W(zle_flags, t_firstname, functionname) \
     { WIDGET_INT | zle_flags, t_firstname, BR(functionname) },
-#include "widgets.list"
+// #include "widgets.list"
+
+/** widgets.list                               **/
+/** widget structures for the internal widgets **/
+
+/* format: W(ZLE_FLAGS, t_firstname, functionname) */
+
+W(0, t_acceptandhold, acceptandhold)
+W(0, t_acceptandinfernexthistory, acceptandinfernexthistory)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_acceptandmenucomplete, acceptandmenucomplete)
+W(0, t_acceptline, acceptline)
+W(0, t_acceptlineanddownhistory, acceptlineanddownhistory)
+W(0, t_acceptsearch, NULL)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_NOTCOMMAND, t_argumentbase, argumentbase)
+W(ZLE_NOTCOMMAND, t_autosuffixremove, handlesuffix)
+W(ZLE_KEEPSUFFIX | ZLE_NOTCOMMAND, t_autosuffixretain, handlesuffix)
+W(0, t_backwardchar, backwardchar)
+W(ZLE_KEEPSUFFIX, t_backwarddeletechar, backwarddeletechar)
+W(ZLE_KEEPSUFFIX, t_backwarddeleteword, backwarddeleteword)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_backwardkillline, backwardkillline)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_backwardkillword, backwardkillword)
+W(0, t_backwardword, backwardword)
+W(0, t_beep, handlefeep)
+W(0, t_beginningofbufferorhistory, beginningofbufferorhistory)
+W(0, t_beginningofhistory, beginningofhistory)
+W(0, t_beginningofline, beginningofline)
+W(0, t_beginningoflinehist, beginningoflinehist)
+W(0, t_capitalizeword, capitalizeword)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_NOTCOMMAND, t_clearscreen, clearscreen)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_completeword, completeword)
+W(ZLE_KEEPSUFFIX, t_copyprevword, copyprevword)
+W(ZLE_KEEPSUFFIX, t_copyprevshellword, copyprevshellword)
+W(ZLE_KEEPSUFFIX, t_copyregionaskill, copyregionaskill)
+W(ZLE_KEEPSUFFIX, t_deletechar, deletechar)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_deletecharorlist, deletecharorlist)
+W(ZLE_KEEPSUFFIX, t_deleteword, deleteword)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_describekeybriefly, describekeybriefly)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_NOTCOMMAND, t_digitargument, digitargument)
+W(0, t_downcaseword, downcaseword)
+W(0, t_downhistory, downhistory)
+W(ZLE_LINEMOVE | ZLE_LASTCOL, t_downlineorhistory, downlineorhistory)
+W(ZLE_LINEMOVE | ZLE_LASTCOL, t_downlineorsearch, downlineorsearch)
+W(0, t_emacsbackwardword, emacsbackwardword)
+W(0, t_emacsforwardword, emacsforwardword)
+W(0, t_endofbufferorhistory, endofbufferorhistory)
+W(0, t_endofhistory, endofhistory)
+W(0, t_endofline, endofline)
+W(0, t_endoflinehist, endoflinehist)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_endoflist, endoflist)
+W(0, t_exchangepointandmark, exchangepointandmark)
+W(0, t_executelastnamedcmd, NULL)
+W(0, t_executenamedcmd, NULL)
+W(0, t_expandcmdpath, expandcmdpath)
+W(0, t_expandhistory, expandhistory)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_expandorcomplete, expandorcomplete)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_expandorcompleteprefix, expandorcompleteprefix)
+W(0, t_expandword, expandword)
+W(0, t_forwardchar, forwardchar)
+W(0, t_forwardword, forwardword)
+W(0, t_getline, zgetline)
+W(0, t_gosmacstransposechars, gosmacstransposechars)
+W(0, t_historybeginningsearchbackward, historybeginningsearchbackward)
+W(0, t_historybeginningsearchforward, historybeginningsearchforward)
+W(0, t_historyincrementalsearchbackward, historyincrementalsearchbackward)
+W(0, t_historyincrementalsearchforward, historyincrementalsearchforward)
+W(0, t_historyincrementalpatternsearchbackward, historyincrementalpatternsearchbackward)
+W(0, t_historyincrementalpatternsearchforward, historyincrementalpatternsearchforward)
+W(0, t_historysearchbackward, historysearchbackward)
+W(0, t_historysearchforward, historysearchforward)
+W(0, t_infernexthistory, infernexthistory)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_insertlastword, insertlastword)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_killbuffer, killbuffer)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_killline, killline)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_killregion, killregion)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_killwholeline, killwholeline)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_killword, killword)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_ISCOMP, t_listchoices, listchoices)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_listexpand, listexpand)
+W(ZLE_KEEPSUFFIX | ZLE_MENUCMP, t_magicspace, magicspace)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_menucomplete, menucomplete)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_menuexpandorcomplete, menuexpandorcomplete)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_NOTCOMMAND, t_negargument, negargument)
+W(0, t_overwritemode, overwritemode)
+W(0, t_poundinsert, poundinsert)
+W(0, t_pushinput, pushinput)
+W(0, t_pushline, pushline)
+W(0, t_pushlineoredit, pushlineoredit)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_quotedinsert, quotedinsert)
+W(0, t_quoteline, quoteline)
+W(0, t_quoteregion, quoteregion)
+W(0, t_readcommand, readcommand)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_recursiveedit, recursiveedit)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_redisplay, redisplay)
+W(ZLE_KEEPSUFFIX, t_redo, redo)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_resetprompt, resetprompt)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_ISCOMP, t_reversemenucomplete, reversemenucomplete)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_runhelp, processcmd)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_selfinsert, selfinsert)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_selfinsertunmeta, selfinsertunmeta)
+W(0, t_sendbreak, sendbreak)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_setmarkcommand, setmarkcommand)
+W(0, t_spellword, spellword)
+W(0, t_setlocalhistory, setlocalhistory)
+W(0, t_transposechars, transposechars)
+W(0, t_transposewords, transposewords)
+W(0, t_undefinedkey, undefinedkey)
+W(ZLE_KEEPSUFFIX, t_undo, undo)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL | ZLE_NOTCOMMAND, t_universalargument, universalargument)
+W(0, t_upcaseword, upcaseword)
+W(0, t_uphistory, uphistory)
+W(ZLE_LINEMOVE | ZLE_LASTCOL, t_uplineorhistory, uplineorhistory)
+W(ZLE_LINEMOVE | ZLE_LASTCOL, t_uplineorsearch, uplineorsearch)
+W(0, t_viaddeol, viaddeol)
+W(0, t_viaddnext, viaddnext)
+W(0, t_vibackwardblankword, vibackwardblankword)
+W(0, t_vibackwardchar, vibackwardchar)
+W(ZLE_KEEPSUFFIX, t_vibackwarddeletechar, vibackwarddeletechar)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_vibackwardkillword, vibackwardkillword)
+W(0, t_vibackwardword, vibackwardword)
+W(0, t_vibeginningofline, vibeginningofline)
+W(0, t_vicapslockpanic, vicapslockpanic)
+W(0, t_vichange, vichange)
+W(0, t_vichangeeol, vichangeeol)
+W(0, t_vichangewholeline, vichangewholeline)
+W(0, t_vicmdmode, vicmdmode)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_videlete, videlete)
+W(ZLE_KEEPSUFFIX, t_videletechar, videletechar)
+W(0, t_vidigitorbeginningofline, vidigitorbeginningofline)
+W(ZLE_LINEMOVE, t_vidownlineorhistory, vidownlineorhistory)
+W(ZLE_LASTCOL, t_viendofline, viendofline)
+W(0, t_vifetchhistory, vifetchhistory)
+W(0, t_vifindnextchar, vifindnextchar)
+W(0, t_vifindnextcharskip, vifindnextcharskip)
+W(0, t_vifindprevchar, vifindprevchar)
+W(0, t_vifindprevcharskip, vifindprevcharskip)
+W(0, t_vifirstnonblank, vifirstnonblank)
+W(0, t_viforwardblankword, viforwardblankword)
+W(0, t_viforwardblankwordend, viforwardblankwordend)
+W(0, t_viforwardchar, viforwardchar)
+W(0, t_viforwardword, viforwardword)
+W(0, t_viforwardwordend, viforwardwordend)
+W(0, t_vigotocolumn, vigotocolumn)
+W(0, t_vigotomark, vigotomark)
+W(0, t_vigotomarkline, vigotomarkline)
+W(0, t_vihistorysearchbackward, vihistorysearchbackward)
+W(0, t_vihistorysearchforward, vihistorysearchforward)
+W(0, t_viindent, viindent)
+W(0, t_viinsert, viinsert)
+W(0, t_viinsertbol, viinsertbol)
+W(0, t_vijoin, vijoin)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_vikilleol, vikilleol)
+W(ZLE_KILL | ZLE_KEEPSUFFIX, t_vikillline, vikillline)
+W(0, t_vimatchbracket, vimatchbracket)
+W(0, t_viopenlineabove, viopenlineabove)
+W(0, t_viopenlinebelow, viopenlinebelow)
+W(0, t_vioperswapcase, vioperswapcase)
+W(0, t_vipoundinsert, vipoundinsert)
+W(ZLE_YANK | ZLE_KEEPSUFFIX, t_viputafter, viputafter)
+W(ZLE_YANK | ZLE_KEEPSUFFIX, t_viputbefore, viputbefore)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX, t_viquotedinsert, viquotedinsert)
+W(0, t_virepeatchange, virepeatchange)
+W(0, t_virepeatfind, virepeatfind)
+W(0, t_virepeatsearch, virepeatsearch)
+W(0, t_vireplace, vireplace)
+W(0, t_vireplacechars, vireplacechars)
+W(0, t_virevrepeatfind, virevrepeatfind)
+W(0, t_virevrepeatsearch, virevrepeatsearch)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_visetbuffer, visetbuffer)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_visetmark, visetmark)
+W(0, t_visubstitute, visubstitute)
+W(0, t_viswapcase, viswapcase)
+W(ZLE_KEEPSUFFIX, t_viundochange, viundochange)
+W(0, t_viunindent, viunindent)
+W(ZLE_LINEMOVE, t_viuplineorhistory, viuplineorhistory)
+W(0, t_viyank, viyank)
+W(0, t_viyankeol, viyankeol)
+W(0, t_viyankwholeline, viyankwholeline)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_whatcursorposition, whatcursorposition)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_whereis, whereis)
+W(ZLE_MENUCMP | ZLE_KEEPSUFFIX | ZLE_LASTCOL, t_whichcommand, processcmd)
+W(ZLE_YANK | ZLE_KEEPSUFFIX, t_yank, yank)
+W(ZLE_YANK | ZLE_KEEPSUFFIX, t_yankpop, yankpop)
+
 #undef W
 };
 
 /*
  * thingies is the table of `known thingies', that exist on startup.
  * Some bits of ZLE rely on some of these thingies always being the
  * ones in this table, rather than doing a name lookup and accepting
  * any semantically identical thingy.  The initial reference count of
  * these thingies is 2: 1 for the widget they name, and 1 extra to
  * make sure they never get deleted.
  */
 
 /**/
 mod_export struct thingy thingies[] = {
 #define T(name, th_flags, w_idget, t_next) \
     { NULL, name, th_flags, 2, w_idget, t_next },
-#include "thingies.list"
+// #include "thingies.list"
+
+/** thingies.list                            **/
+/** thingy structures for the known thingies **/
+
+/* format: T("name", TH_FLAGS, w_widget, t_nextthingy) */
+
+T("accept-and-hold", 0, w_acceptandhold, t_Dacceptandhold)
+T("accept-and-infer-next-history", 0, w_acceptandinfernexthistory, t_Dacceptandinfernexthistory)
+T("accept-and-menu-complete", 0, w_acceptandmenucomplete, t_Dacceptandmenucomplete)
+T("accept-line", 0, w_acceptline, t_Dacceptline)
+T("accept-line-and-down-history", 0, w_acceptlineanddownhistory, t_Dacceptlineanddownhistory)
+T("accept-search", 0, w_acceptsearch, t_Dacceptsearch)
+T("argument-base", 0, w_argumentbase, t_Dargumentbase)
+T("auto-suffix-remove", 0, w_autosuffixremove, t_Dautosuffixremove)
+T("auto-suffix-retain", 0, w_autosuffixretain, t_Dautosuffixretain)
+T("backward-char", 0, w_backwardchar, t_Dbackwardchar)
+T("backward-delete-char", 0, w_backwarddeletechar, t_Dbackwarddeletechar)
+T("backward-delete-word", 0, w_backwarddeleteword, t_Dbackwarddeleteword)
+T("backward-kill-line", 0, w_backwardkillline, t_Dbackwardkillline)
+T("backward-kill-word", 0, w_backwardkillword, t_Dbackwardkillword)
+T("backward-word", 0, w_backwardword, t_Dbackwardword)
+T("beep", 0, w_beep, t_Dbeep)
+T("beginning-of-buffer-or-history", 0, w_beginningofbufferorhistory, t_Dbeginningofbufferorhistory)
+T("beginning-of-history", 0, w_beginningofhistory, t_Dbeginningofhistory)
+T("beginning-of-line", 0, w_beginningofline, t_Dbeginningofline)
+T("beginning-of-line-hist", 0, w_beginningoflinehist, t_Dbeginningoflinehist)
+T("capitalize-word", 0, w_capitalizeword, t_Dcapitalizeword)
+T("clear-screen", 0, w_clearscreen, t_Dclearscreen)
+T("complete-word", 0, w_completeword, t_Dcompleteword)
+T("copy-prev-word", 0, w_copyprevword, t_Dcopyprevword)
+T("copy-prev-shell-word", 0, w_copyprevshellword, t_Dcopyprevshellword)
+T("copy-region-as-kill", 0, w_copyregionaskill, t_Dcopyregionaskill)
+T("delete-char", 0, w_deletechar, t_Ddeletechar)
+T("delete-char-or-list", 0, w_deletecharorlist, t_Ddeletecharorlist)
+T("delete-word", 0, w_deleteword, t_Ddeleteword)
+T("describe-key-briefly", 0, w_describekeybriefly, t_Ddescribekeybriefly)
+T("digit-argument", 0, w_digitargument, t_Ddigitargument)
+T("down-case-word", 0, w_downcaseword, t_Ddowncaseword)
+T("down-history", 0, w_downhistory, t_Ddownhistory)
+T("down-line-or-history", 0, w_downlineorhistory, t_Ddownlineorhistory)
+T("down-line-or-search", 0, w_downlineorsearch, t_Ddownlineorsearch)
+T("emacs-backward-word", 0, w_emacsbackwardword, t_Demacsbackwardword)
+T("emacs-forward-word", 0, w_emacsforwardword, t_Demacsforwardword)
+T("end-of-buffer-or-history", 0, w_endofbufferorhistory, t_Dendofbufferorhistory)
+T("end-of-history", 0, w_endofhistory, t_Dendofhistory)
+T("end-of-line", 0, w_endofline, t_Dendofline)
+T("end-of-line-hist", 0, w_endoflinehist, t_Dendoflinehist)
+T("end-of-list", 0, w_endoflist, t_Dendoflist)
+T("exchange-point-and-mark", 0, w_exchangepointandmark, t_Dexchangepointandmark)
+T("execute-last-named-cmd", 0, w_executelastnamedcmd, t_Dexecutelastnamedcmd)
+T("execute-named-cmd", 0, w_executenamedcmd, t_Dexecutenamedcmd)
+T("expand-cmd-path", 0, w_expandcmdpath, t_Dexpandcmdpath)
+T("expand-history", 0, w_expandhistory, t_Dexpandhistory)
+T("expand-or-complete", 0, w_expandorcomplete, t_Dexpandorcomplete)
+T("expand-or-complete-prefix", 0, w_expandorcompleteprefix, t_Dexpandorcompleteprefix)
+T("expand-word", 0, w_expandword, t_Dexpandword)
+T("forward-char", 0, w_forwardchar, t_Dforwardchar)
+T("forward-word", 0, w_forwardword, t_Dforwardword)
+T("get-line", 0, w_getline, t_Dgetline)
+T("gosmacs-transpose-chars", 0, w_gosmacstransposechars, t_Dgosmacstransposechars)
+T("history-beginning-search-backward", 0, w_historybeginningsearchbackward, t_Dhistorybeginningsearchbackward)
+T("history-beginning-search-forward", 0, w_historybeginningsearchforward, t_Dhistorybeginningsearchforward)
+T("history-incremental-search-backward", 0, w_historyincrementalsearchbackward, t_Dhistoryincrementalsearchbackward)
+T("history-incremental-search-forward", 0, w_historyincrementalsearchforward, t_Dhistoryincrementalsearchforward)
+T("history-incremental-pattern-search-backward", 0, w_historyincrementalpatternsearchbackward, t_Dhistoryincrementalpatternsearchbackward)
+T("history-incremental-pattern-search-forward", 0, w_historyincrementalpatternsearchforward, t_Dhistoryincrementalpatternsearchforward)
+T("history-search-backward", 0, w_historysearchbackward, t_Dhistorysearchbackward)
+T("history-search-forward", 0, w_historysearchforward, t_Dhistorysearchforward)
+T("infer-next-history", 0, w_infernexthistory, t_Dinfernexthistory)
+T("insert-last-word", 0, w_insertlastword, t_Dinsertlastword)
+T("kill-buffer", 0, w_killbuffer, t_Dkillbuffer)
+T("kill-line", 0, w_killline, t_Dkillline)
+T("kill-region", 0, w_killregion, t_Dkillregion)
+T("kill-whole-line", 0, w_killwholeline, t_Dkillwholeline)
+T("kill-word", 0, w_killword, t_Dkillword)
+T("list-choices", 0, w_listchoices, t_Dlistchoices)
+T("list-expand", 0, w_listexpand, t_Dlistexpand)
+T("magic-space", 0, w_magicspace, t_Dmagicspace)
+T("menu-complete", 0, w_menucomplete, t_Dmenucomplete)
+T("menu-expand-or-complete", 0, w_menuexpandorcomplete, t_Dmenuexpandorcomplete)
+T("neg-argument", 0, w_negargument, t_Dnegargument)
+T("overwrite-mode", 0, w_overwritemode, t_Doverwritemode)
+T("pound-insert", 0, w_poundinsert, t_Dpoundinsert)
+T("push-input", 0, w_pushinput, t_Dpushinput)
+T("push-line", 0, w_pushline, t_Dpushline)
+T("push-line-or-edit", 0, w_pushlineoredit, t_Dpushlineoredit)
+T("quoted-insert", 0, w_quotedinsert, t_Dquotedinsert)
+T("quote-line", 0, w_quoteline, t_Dquoteline)
+T("quote-region", 0, w_quoteregion, t_Dquoteregion)
+T("read-command", 0, w_readcommand, t_Dreadcommand)
+T("recursive-edit", 0, w_recursiveedit, t_Drecursiveedit)
+T("redisplay", 0, w_redisplay, t_Dredisplay)
+T("redo", 0, w_redo, t_Dredo)
+T("reset-prompt", 0, w_resetprompt, t_Dresetprompt)
+T("reverse-menu-complete", 0, w_reversemenucomplete, t_Dreversemenucomplete)
+T("run-help", 0, w_runhelp, t_Drunhelp)
+T("self-insert", 0, w_selfinsert, t_Dselfinsert)
+T("self-insert-unmeta", 0, w_selfinsertunmeta, t_Dselfinsertunmeta)
+T("send-break", 0, w_sendbreak, t_Dsendbreak)
+T("set-mark-command", 0, w_setmarkcommand, t_Dsetmarkcommand)
+T("spell-word", 0, w_spellword, t_Dspellword)
+T("set-local-history", 0, w_setlocalhistory, t_Dsetlocalhistory)
+T("transpose-chars", 0, w_transposechars, t_Dtransposechars)
+T("transpose-words", 0, w_transposewords, t_Dtransposewords)
+T("undefined-key", 0, w_undefinedkey, t_Dundefinedkey)
+T("undo", 0, w_undo, t_Dundo)
+T("universal-argument", 0, w_universalargument, t_Duniversalargument)
+T("up-case-word", 0, w_upcaseword, t_Dupcaseword)
+T("up-history", 0, w_uphistory, t_Duphistory)
+T("up-line-or-history", 0, w_uplineorhistory, t_Duplineorhistory)
+T("up-line-or-search", 0, w_uplineorsearch, t_Duplineorsearch)
+T("vi-add-eol", 0, w_viaddeol, t_Dviaddeol)
+T("vi-add-next", 0, w_viaddnext, t_Dviaddnext)
+T("vi-backward-blank-word", 0, w_vibackwardblankword, t_Dvibackwardblankword)
+T("vi-backward-char", 0, w_vibackwardchar, t_Dvibackwardchar)
+T("vi-backward-delete-char", 0, w_vibackwarddeletechar, t_Dvibackwarddeletechar)
+T("vi-backward-kill-word", 0, w_vibackwardkillword, t_Dvibackwardkillword)
+T("vi-backward-word", 0, w_vibackwardword, t_Dvibackwardword)
+T("vi-beginning-of-line", 0, w_vibeginningofline, t_Dvibeginningofline)
+T("vi-caps-lock-panic", 0, w_vicapslockpanic, t_Dvicapslockpanic)
+T("vi-change", 0, w_vichange, t_Dvichange)
+T("vi-change-eol", 0, w_vichangeeol, t_Dvichangeeol)
+T("vi-change-whole-line", 0, w_vichangewholeline, t_Dvichangewholeline)
+T("vi-cmd-mode", 0, w_vicmdmode, t_Dvicmdmode)
+T("vi-delete", 0, w_videlete, t_Dvidelete)
+T("vi-delete-char", 0, w_videletechar, t_Dvideletechar)
+T("vi-digit-or-beginning-of-line", 0, w_vidigitorbeginningofline, t_Dvidigitorbeginningofline)
+T("vi-down-line-or-history", 0, w_vidownlineorhistory, t_Dvidownlineorhistory)
+T("vi-end-of-line", 0, w_viendofline, t_Dviendofline)
+T("vi-fetch-history", 0, w_vifetchhistory, t_Dvifetchhistory)
+T("vi-find-next-char", 0, w_vifindnextchar, t_Dvifindnextchar)
+T("vi-find-next-char-skip", 0, w_vifindnextcharskip, t_Dvifindnextcharskip)
+T("vi-find-prev-char", 0, w_vifindprevchar, t_Dvifindprevchar)
+T("vi-find-prev-char-skip", 0, w_vifindprevcharskip, t_Dvifindprevcharskip)
+T("vi-first-non-blank", 0, w_vifirstnonblank, t_Dvifirstnonblank)
+T("vi-forward-blank-word", 0, w_viforwardblankword, t_Dviforwardblankword)
+T("vi-forward-blank-word-end", 0, w_viforwardblankwordend, t_Dviforwardblankwordend)
+T("vi-forward-char", 0, w_viforwardchar, t_Dviforwardchar)
+T("vi-forward-word", 0, w_viforwardword, t_Dviforwardword)
+T("vi-forward-word-end", 0, w_viforwardwordend, t_Dviforwardwordend)
+T("vi-goto-column", 0, w_vigotocolumn, t_Dvigotocolumn)
+T("vi-goto-mark", 0, w_vigotomark, t_Dvigotomark)
+T("vi-goto-mark-line", 0, w_vigotomarkline, t_Dvigotomarkline)
+T("vi-history-search-backward", 0, w_vihistorysearchbackward, t_Dvihistorysearchbackward)
+T("vi-history-search-forward", 0, w_vihistorysearchforward, t_Dvihistorysearchforward)
+T("vi-indent", 0, w_viindent, t_Dviindent)
+T("vi-insert", 0, w_viinsert, t_Dviinsert)
+T("vi-insert-bol", 0, w_viinsertbol, t_Dviinsertbol)
+T("vi-join", 0, w_vijoin, t_Dvijoin)
+T("vi-kill-eol", 0, w_vikilleol, t_Dvikilleol)
+T("vi-kill-line", 0, w_vikillline, t_Dvikillline)
+T("vi-match-bracket", 0, w_vimatchbracket, t_Dvimatchbracket)
+T("vi-open-line-above", 0, w_viopenlineabove, t_Dviopenlineabove)
+T("vi-open-line-below", 0, w_viopenlinebelow, t_Dviopenlinebelow)
+T("vi-oper-swap-case", 0, w_vioperswapcase, t_Dvioperswapcase)
+T("vi-pound-insert", 0, w_vipoundinsert, t_Dvipoundinsert)
+T("vi-put-after", 0, w_viputafter, t_Dviputafter)
+T("vi-put-before", 0, w_viputbefore, t_Dviputbefore)
+T("vi-quoted-insert", 0, w_viquotedinsert, t_Dviquotedinsert)
+T("vi-repeat-change", 0, w_virepeatchange, t_Dvirepeatchange)
+T("vi-repeat-find", 0, w_virepeatfind, t_Dvirepeatfind)
+T("vi-repeat-search", 0, w_virepeatsearch, t_Dvirepeatsearch)
+T("vi-replace", 0, w_vireplace, t_Dvireplace)
+T("vi-replace-chars", 0, w_vireplacechars, t_Dvireplacechars)
+T("vi-rev-repeat-find", 0, w_virevrepeatfind, t_Dvirevrepeatfind)
+T("vi-rev-repeat-search", 0, w_virevrepeatsearch, t_Dvirevrepeatsearch)
+T("vi-set-buffer", 0, w_visetbuffer, t_Dvisetbuffer)
+T("vi-set-mark", 0, w_visetmark, t_Dvisetmark)
+T("vi-substitute", 0, w_visubstitute, t_Dvisubstitute)
+T("vi-swap-case", 0, w_viswapcase, t_Dviswapcase)
+T("vi-undo-change", 0, w_viundochange, t_Dviundochange)
+T("vi-unindent", 0, w_viunindent, t_Dviunindent)
+T("vi-up-line-or-history", 0, w_viuplineorhistory, t_Dviuplineorhistory)
+T("vi-yank", 0, w_viyank, t_Dviyank)
+T("vi-yank-eol", 0, w_viyankeol, t_Dviyankeol)
+T("vi-yank-whole-line", 0, w_viyankwholeline, t_Dviyankwholeline)
+T("what-cursor-position", 0, w_whatcursorposition, t_Dwhatcursorposition)
+T("where-is", 0, w_whereis, t_Dwhereis)
+T("which-command", 0, w_whichcommand, t_Dwhichcommand)
+T("yank", 0, w_yank, t_Dyank)
+T("yank-pop", 0, w_yankpop, t_Dyankpop)
+T(".accept-and-hold", TH_IMMORTAL, w_acceptandhold, t_acceptandhold)
+T(".accept-and-infer-next-history", TH_IMMORTAL, w_acceptandinfernexthistory, t_acceptandinfernexthistory)
+T(".accept-and-menu-complete", TH_IMMORTAL, w_acceptandmenucomplete, t_acceptandmenucomplete)
+T(".accept-line", TH_IMMORTAL, w_acceptline, t_acceptline)
+T(".accept-line-and-down-history", TH_IMMORTAL, w_acceptlineanddownhistory, t_acceptlineanddownhistory)
+T(".accept-search", TH_IMMORTAL, w_acceptsearch, t_acceptsearch)
+T(".argument-base", TH_IMMORTAL, w_argumentbase, t_argumentbase)
+T(".auto-suffix-remove", TH_IMMORTAL, w_autosuffixremove, t_autosuffixremove)
+T(".auto-suffix-retain", TH_IMMORTAL, w_autosuffixretain, t_autosuffixretain)
+T(".backward-char", TH_IMMORTAL, w_backwardchar, t_backwardchar)
+T(".backward-delete-char", TH_IMMORTAL, w_backwarddeletechar, t_backwarddeletechar)
+T(".backward-delete-word", TH_IMMORTAL, w_backwarddeleteword, t_backwarddeleteword)
+T(".backward-kill-line", TH_IMMORTAL, w_backwardkillline, t_backwardkillline)
+T(".backward-kill-word", TH_IMMORTAL, w_backwardkillword, t_backwardkillword)
+T(".backward-word", TH_IMMORTAL, w_backwardword, t_backwardword)
+T(".beep", TH_IMMORTAL, w_beep, t_beep)
+T(".beginning-of-buffer-or-history", TH_IMMORTAL, w_beginningofbufferorhistory, t_beginningofbufferorhistory)
+T(".beginning-of-history", TH_IMMORTAL, w_beginningofhistory, t_beginningofhistory)
+T(".beginning-of-line", TH_IMMORTAL, w_beginningofline, t_beginningofline)
+T(".beginning-of-line-hist", TH_IMMORTAL, w_beginningoflinehist, t_beginningoflinehist)
+T(".capitalize-word", TH_IMMORTAL, w_capitalizeword, t_capitalizeword)
+T(".clear-screen", TH_IMMORTAL, w_clearscreen, t_clearscreen)
+T(".complete-word", TH_IMMORTAL, w_completeword, t_completeword)
+T(".copy-prev-word", TH_IMMORTAL, w_copyprevword, t_copyprevword)
+T(".copy-prev-shell-word", TH_IMMORTAL, w_copyprevshellword, t_copyprevshellword)
+T(".copy-region-as-kill", TH_IMMORTAL, w_copyregionaskill, t_copyregionaskill)
+T(".delete-char", TH_IMMORTAL, w_deletechar, t_deletechar)
+T(".delete-char-or-list", TH_IMMORTAL, w_deletecharorlist, t_deletecharorlist)
+T(".delete-word", TH_IMMORTAL, w_deleteword, t_deleteword)
+T(".describe-key-briefly", TH_IMMORTAL, w_describekeybriefly, t_describekeybriefly)
+T(".digit-argument", TH_IMMORTAL, w_digitargument, t_digitargument)
+T(".down-case-word", TH_IMMORTAL, w_downcaseword, t_downcaseword)
+T(".down-history", TH_IMMORTAL, w_downhistory, t_downhistory)
+T(".down-line-or-history", TH_IMMORTAL, w_downlineorhistory, t_downlineorhistory)
+T(".down-line-or-search", TH_IMMORTAL, w_downlineorsearch, t_downlineorsearch)
+T(".emacs-backward-word", TH_IMMORTAL, w_emacsbackwardword, t_emacsbackwardword)
+T(".emacs-forward-word", TH_IMMORTAL, w_emacsforwardword, t_emacsforwardword)
+T(".end-of-buffer-or-history", TH_IMMORTAL, w_endofbufferorhistory, t_endofbufferorhistory)
+T(".end-of-history", TH_IMMORTAL, w_endofhistory, t_endofhistory)
+T(".end-of-line", TH_IMMORTAL, w_endofline, t_endofline)
+T(".end-of-line-hist", TH_IMMORTAL, w_endoflinehist, t_endoflinehist)
+T(".end-of-list", TH_IMMORTAL, w_endoflist, t_endoflist)
+T(".exchange-point-and-mark", TH_IMMORTAL, w_exchangepointandmark, t_exchangepointandmark)
+T(".execute-last-named-cmd", TH_IMMORTAL, w_executelastnamedcmd, t_executelastnamedcmd)
+T(".execute-named-cmd", TH_IMMORTAL, w_executenamedcmd, t_executenamedcmd)
+T(".expand-cmd-path", TH_IMMORTAL, w_expandcmdpath, t_expandcmdpath)
+T(".expand-history", TH_IMMORTAL, w_expandhistory, t_expandhistory)
+T(".expand-or-complete", TH_IMMORTAL, w_expandorcomplete, t_expandorcomplete)
+T(".expand-or-complete-prefix", TH_IMMORTAL, w_expandorcompleteprefix, t_expandorcompleteprefix)
+T(".expand-word", TH_IMMORTAL, w_expandword, t_expandword)
+T(".forward-char", TH_IMMORTAL, w_forwardchar, t_forwardchar)
+T(".forward-word", TH_IMMORTAL, w_forwardword, t_forwardword)
+T(".get-line", TH_IMMORTAL, w_getline, t_getline)
+T(".gosmacs-transpose-chars", TH_IMMORTAL, w_gosmacstransposechars, t_gosmacstransposechars)
+T(".history-beginning-search-backward", TH_IMMORTAL, w_historybeginningsearchbackward, t_historybeginningsearchbackward)
+T(".history-beginning-search-forward", TH_IMMORTAL, w_historybeginningsearchforward, t_historybeginningsearchforward)
+T(".history-incremental-search-backward", TH_IMMORTAL, w_historyincrementalsearchbackward, t_historyincrementalsearchbackward)
+T(".history-incremental-search-forward", TH_IMMORTAL, w_historyincrementalsearchforward, t_historyincrementalsearchforward)
+T(".history-incremental-pattern-search-backward", TH_IMMORTAL, w_historyincrementalpatternsearchbackward, t_historyincrementalpatternsearchbackward)
+T(".history-incremental-pattern-search-forward", TH_IMMORTAL, w_historyincrementalpatternsearchforward, t_historyincrementalpatternsearchforward)
+T(".history-search-backward", TH_IMMORTAL, w_historysearchbackward, t_historysearchbackward)
+T(".history-search-forward", TH_IMMORTAL, w_historysearchforward, t_historysearchforward)
+T(".infer-next-history", TH_IMMORTAL, w_infernexthistory, t_infernexthistory)
+T(".insert-last-word", TH_IMMORTAL, w_insertlastword, t_insertlastword)
+T(".kill-buffer", TH_IMMORTAL, w_killbuffer, t_killbuffer)
+T(".kill-line", TH_IMMORTAL, w_killline, t_killline)
+T(".kill-region", TH_IMMORTAL, w_killregion, t_killregion)
+T(".kill-whole-line", TH_IMMORTAL, w_killwholeline, t_killwholeline)
+T(".kill-word", TH_IMMORTAL, w_killword, t_killword)
+T(".list-choices", TH_IMMORTAL, w_listchoices, t_listchoices)
+T(".list-expand", TH_IMMORTAL, w_listexpand, t_listexpand)
+T(".magic-space", TH_IMMORTAL, w_magicspace, t_magicspace)
+T(".menu-complete", TH_IMMORTAL, w_menucomplete, t_menucomplete)
+T(".menu-expand-or-complete", TH_IMMORTAL, w_menuexpandorcomplete, t_menuexpandorcomplete)
+T(".neg-argument", TH_IMMORTAL, w_negargument, t_negargument)
+T(".overwrite-mode", TH_IMMORTAL, w_overwritemode, t_overwritemode)
+T(".pound-insert", TH_IMMORTAL, w_poundinsert, t_poundinsert)
+T(".push-input", TH_IMMORTAL, w_pushinput, t_pushinput)
+T(".push-line", TH_IMMORTAL, w_pushline, t_pushline)
+T(".push-line-or-edit", TH_IMMORTAL, w_pushlineoredit, t_pushlineoredit)
+T(".quoted-insert", TH_IMMORTAL, w_quotedinsert, t_quotedinsert)
+T(".quote-line", TH_IMMORTAL, w_quoteline, t_quoteline)
+T(".quote-region", TH_IMMORTAL, w_quoteregion, t_quoteregion)
+T(".read-command", TH_IMMORTAL, w_readcommand, t_readcommand)
+T(".recursive-edit", TH_IMMORTAL, w_recursiveedit, t_recursiveedit)
+T(".redisplay", TH_IMMORTAL, w_redisplay, t_redisplay)
+T(".redo", TH_IMMORTAL, w_redo, t_redo)
+T(".reset-prompt", TH_IMMORTAL, w_resetprompt, t_resetprompt)
+T(".reverse-menu-complete", TH_IMMORTAL, w_reversemenucomplete, t_reversemenucomplete)
+T(".run-help", TH_IMMORTAL, w_runhelp, t_runhelp)
+T(".self-insert", TH_IMMORTAL, w_selfinsert, t_selfinsert)
+T(".self-insert-unmeta", TH_IMMORTAL, w_selfinsertunmeta, t_selfinsertunmeta)
+T(".send-break", TH_IMMORTAL, w_sendbreak, t_sendbreak)
+T(".set-mark-command", TH_IMMORTAL, w_setmarkcommand, t_setmarkcommand)
+T(".spell-word", TH_IMMORTAL, w_spellword, t_spellword)
+T(".set-local-history", TH_IMMORTAL, w_setlocalhistory, t_setlocalhistory)
+T(".transpose-chars", TH_IMMORTAL, w_transposechars, t_transposechars)
+T(".transpose-words", TH_IMMORTAL, w_transposewords, t_transposewords)
+T(".undefined-key", TH_IMMORTAL, w_undefinedkey, t_undefinedkey)
+T(".undo", TH_IMMORTAL, w_undo, t_undo)
+T(".universal-argument", TH_IMMORTAL, w_universalargument, t_universalargument)
+T(".up-case-word", TH_IMMORTAL, w_upcaseword, t_upcaseword)
+T(".up-history", TH_IMMORTAL, w_uphistory, t_uphistory)
+T(".up-line-or-history", TH_IMMORTAL, w_uplineorhistory, t_uplineorhistory)
+T(".up-line-or-search", TH_IMMORTAL, w_uplineorsearch, t_uplineorsearch)
+T(".vi-add-eol", TH_IMMORTAL, w_viaddeol, t_viaddeol)
+T(".vi-add-next", TH_IMMORTAL, w_viaddnext, t_viaddnext)
+T(".vi-backward-blank-word", TH_IMMORTAL, w_vibackwardblankword, t_vibackwardblankword)
+T(".vi-backward-char", TH_IMMORTAL, w_vibackwardchar, t_vibackwardchar)
+T(".vi-backward-delete-char", TH_IMMORTAL, w_vibackwarddeletechar, t_vibackwarddeletechar)
+T(".vi-backward-kill-word", TH_IMMORTAL, w_vibackwardkillword, t_vibackwardkillword)
+T(".vi-backward-word", TH_IMMORTAL, w_vibackwardword, t_vibackwardword)
+T(".vi-beginning-of-line", TH_IMMORTAL, w_vibeginningofline, t_vibeginningofline)
+T(".vi-caps-lock-panic", TH_IMMORTAL, w_vicapslockpanic, t_vicapslockpanic)
+T(".vi-change", TH_IMMORTAL, w_vichange, t_vichange)
+T(".vi-change-eol", TH_IMMORTAL, w_vichangeeol, t_vichangeeol)
+T(".vi-change-whole-line", TH_IMMORTAL, w_vichangewholeline, t_vichangewholeline)
+T(".vi-cmd-mode", TH_IMMORTAL, w_vicmdmode, t_vicmdmode)
+T(".vi-delete", TH_IMMORTAL, w_videlete, t_videlete)
+T(".vi-delete-char", TH_IMMORTAL, w_videletechar, t_videletechar)
+T(".vi-digit-or-beginning-of-line", TH_IMMORTAL, w_vidigitorbeginningofline, t_vidigitorbeginningofline)
+T(".vi-down-line-or-history", TH_IMMORTAL, w_vidownlineorhistory, t_vidownlineorhistory)
+T(".vi-end-of-line", TH_IMMORTAL, w_viendofline, t_viendofline)
+T(".vi-fetch-history", TH_IMMORTAL, w_vifetchhistory, t_vifetchhistory)
+T(".vi-find-next-char", TH_IMMORTAL, w_vifindnextchar, t_vifindnextchar)
+T(".vi-find-next-char-skip", TH_IMMORTAL, w_vifindnextcharskip, t_vifindnextcharskip)
+T(".vi-find-prev-char", TH_IMMORTAL, w_vifindprevchar, t_vifindprevchar)
+T(".vi-find-prev-char-skip", TH_IMMORTAL, w_vifindprevcharskip, t_vifindprevcharskip)
+T(".vi-first-non-blank", TH_IMMORTAL, w_vifirstnonblank, t_vifirstnonblank)
+T(".vi-forward-blank-word", TH_IMMORTAL, w_viforwardblankword, t_viforwardblankword)
+T(".vi-forward-blank-word-end", TH_IMMORTAL, w_viforwardblankwordend, t_viforwardblankwordend)
+T(".vi-forward-char", TH_IMMORTAL, w_viforwardchar, t_viforwardchar)
+T(".vi-forward-word", TH_IMMORTAL, w_viforwardword, t_viforwardword)
+T(".vi-forward-word-end", TH_IMMORTAL, w_viforwardwordend, t_viforwardwordend)
+T(".vi-goto-column", TH_IMMORTAL, w_vigotocolumn, t_vigotocolumn)
+T(".vi-goto-mark", TH_IMMORTAL, w_vigotomark, t_vigotomark)
+T(".vi-goto-mark-line", TH_IMMORTAL, w_vigotomarkline, t_vigotomarkline)
+T(".vi-history-search-backward", TH_IMMORTAL, w_vihistorysearchbackward, t_vihistorysearchbackward)
+T(".vi-history-search-forward", TH_IMMORTAL, w_vihistorysearchforward, t_vihistorysearchforward)
+T(".vi-indent", TH_IMMORTAL, w_viindent, t_viindent)
+T(".vi-insert", TH_IMMORTAL, w_viinsert, t_viinsert)
+T(".vi-insert-bol", TH_IMMORTAL, w_viinsertbol, t_viinsertbol)
+T(".vi-join", TH_IMMORTAL, w_vijoin, t_vijoin)
+T(".vi-kill-eol", TH_IMMORTAL, w_vikilleol, t_vikilleol)
+T(".vi-kill-line", TH_IMMORTAL, w_vikillline, t_vikillline)
+T(".vi-match-bracket", TH_IMMORTAL, w_vimatchbracket, t_vimatchbracket)
+T(".vi-open-line-above", TH_IMMORTAL, w_viopenlineabove, t_viopenlineabove)
+T(".vi-open-line-below", TH_IMMORTAL, w_viopenlinebelow, t_viopenlinebelow)
+T(".vi-oper-swap-case", TH_IMMORTAL, w_vioperswapcase, t_vioperswapcase)
+T(".vi-pound-insert", TH_IMMORTAL, w_vipoundinsert, t_vipoundinsert)
+T(".vi-put-after", TH_IMMORTAL, w_viputafter, t_viputafter)
+T(".vi-put-before", TH_IMMORTAL, w_viputbefore, t_viputbefore)
+T(".vi-quoted-insert", TH_IMMORTAL, w_viquotedinsert, t_viquotedinsert)
+T(".vi-repeat-change", TH_IMMORTAL, w_virepeatchange, t_virepeatchange)
+T(".vi-repeat-find", TH_IMMORTAL, w_virepeatfind, t_virepeatfind)
+T(".vi-repeat-search", TH_IMMORTAL, w_virepeatsearch, t_virepeatsearch)
+T(".vi-replace", TH_IMMORTAL, w_vireplace, t_vireplace)
+T(".vi-replace-chars", TH_IMMORTAL, w_vireplacechars, t_vireplacechars)
+T(".vi-rev-repeat-find", TH_IMMORTAL, w_virevrepeatfind, t_virevrepeatfind)
+T(".vi-rev-repeat-search", TH_IMMORTAL, w_virevrepeatsearch, t_virevrepeatsearch)
+T(".vi-set-buffer", TH_IMMORTAL, w_visetbuffer, t_visetbuffer)
+T(".vi-set-mark", TH_IMMORTAL, w_visetmark, t_visetmark)
+T(".vi-substitute", TH_IMMORTAL, w_visubstitute, t_visubstitute)
+T(".vi-swap-case", TH_IMMORTAL, w_viswapcase, t_viswapcase)
+T(".vi-undo-change", TH_IMMORTAL, w_viundochange, t_viundochange)
+T(".vi-unindent", TH_IMMORTAL, w_viunindent, t_viunindent)
+T(".vi-up-line-or-history", TH_IMMORTAL, w_viuplineorhistory, t_viuplineorhistory)
+T(".vi-yank", TH_IMMORTAL, w_viyank, t_viyank)
+T(".vi-yank-eol", TH_IMMORTAL, w_viyankeol, t_viyankeol)
+T(".vi-yank-whole-line", TH_IMMORTAL, w_viyankwholeline, t_viyankwholeline)
+T(".what-cursor-position", TH_IMMORTAL, w_whatcursorposition, t_whatcursorposition)
+T(".where-is", TH_IMMORTAL, w_whereis, t_whereis)
+T(".which-command", TH_IMMORTAL, w_whichcommand, t_whichcommand)
+T(".yank", TH_IMMORTAL, w_yank, t_yank)
+T(".yank-pop", TH_IMMORTAL, w_yankpop, t_yankpop)
+
 #undef T
     { NULL, NULL, 0, 0, NULL, NULL }
 };
 
 /*
  * Default key binding tables:
  *
  * In these tables, each element is bound to a single thingy, the index
  * of which in the above table is stored here.
  */
