sudo: required
dist: trusty

language: node_js

matrix:
  include:
    - os: osx
      node_js: 6
    - os: linux
      node_js: 6
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - rpm
      - bsdtar

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

before_script:
  - npm prune

after_success:
  - npm run dist

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
